version: '3'
services:
    web:
        build:
            dockerfile: ./Dockerfile
            context: ./
        volumes:
            - ./ui/cli/static:/cmd/cli/static
        command: /server -host=0.0.0.0 -port=80 -static=/ui/cli/static
        ports:
            - 80:80
