version: '3'
services:
    web:
        build:
            dockerfile: ./Dockerfile
            context: ./
        volumes:
            - ./cmd/client/static:/cmd/client/static
        command: /server -host=0.0.0.0 -port=80 -static=/cmd/client/static
        ports:
            - 80:80
