version: '3'
services:
    web:
        build:
            dockerfile: ./Dockerfile.dev
            context: ./
        volumes:
            - ./:/src
            - $GOPATH/pkg/mod:/go/pkg/mod
        entrypoint: "watcher -run cmd/server.go"
        ports:
            - 80:80
