version: '3'
services:
    web:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./web/client/static:/client/static
        command: /server -host=0.0.0.0 -port=80 -static=/client/static
        ports:
            - 80:80
